# 워크플로우 이름
name: Deploy API to Azure Function App

# 언제 실행할지 정의: main 브랜치에 코드가 push 될 때
on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행을 위한 버튼 추가

# 수정하기 쉽도록 환경 변수로 앱 이름과 폴더 경로를 지정
env:
  AZURE_FUNCTIONAPP_NAME: 'GetRandomMessage'  # ★ Azure Portal의 이름과 정확히 일치해야 함
  API_DIRECTORY: 'api'                      # 함수 코드가 있는 폴더

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1. GitHub 저장소의 코드를 가져옴
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '${{ env.API_DIRECTORY }}/package-lock.json'

      # 3. 'api' 폴더로 이동해서 의존성 설치
      - name: npm install in api directory
        run: npm install
        working-directory: ${{ env.API_DIRECTORY }}
      
      # (선택사항) 빌드 스텝이 필요한 경우 여기에 추가
      # - name: Build project
      #   run: npm run build --if-present
      #   working-directory: ${{ env.API_DIRECTORY }}

      # 4. Azure에 배포
      # ★★★ 수정된 부분 ★★★
      # working-directory를 'api'로 지정하고 package를 '.'으로 설정하여
      # 'api' 폴더의 내용물만 압축하여 배포하도록 수정합니다.
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: . # 현재 작업 디렉터리의 모든 것을 패키징
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          clean: true
        working-directory: ${{ env.API_DIRECTORY }}